

#define INTERNAL_CAPACITANCE_IN_PF (1*14) // 6 pf is the ADC internal cap also
#define INTERNAL_CAPACITANCE_IN_PF_HIGH (1*29)
#define INTERNAL_INDUCTANCE_IN_UF  (130)
#define WIRE_RESISTANCE_AND_INTERNAL 24


