#include "generated/cap_decl.h"
#include "generated/resistor_decl.h"
#include "generated/splash_decl.h"
#include "generated/diode_decl.h"
#include "generated/coil_decl.h"
#include "generated/Nmosfet2_decl.h"
#include "generated/Pmosfet_decl.h"
