#include "Arduino.h"
#include "assets.h"
#include "generated/cap_compressed.h"
#include "generated/resistor_compressed.h"
#include "generated/splash_compressed.h"
#include "generated/diode_compressed.h"
#include "generated/coil_compressed.h"
